hw02
DaryaGrygorova/goit-nodeJS-REST_API pull request #1
Opened 2022-10-22 13:39 UTC by DaryaGrygorova

2022-10-22 17:12 UTC, Eastvarga commented on .env_exemple
> +PORT=
.env Файли змінних середовищ повинні бути у виключеннях .gitignore та не потропляти у репозіторій. Тому що це зазвичай ключи доступу - їх ніхто сторонній не має право бачити, це небезпечно.

2022-10-22 17:28 UTC, Eastvarga commented on models/contacts.js
> +    return JSON.parse(res);
const res = await fs.readFile(contactsPath, textFormat);
    return JSON.parse(res);
цей вираз краще винести в окрему функцію, котру можна буде перевикористати в інших функціях де потрібно отримати масив з файлу

2022-10-22 17:29 UTC, Eastvarga commented on models/contacts.js
> +    const data = JSON.parse(res);
стосовно коментарія віще

2022-10-22 17:41 UTC, Eastvarga commented on models/contacts.js
> +    return contact;
Не потрібна додаткова логіка
якщо ви повертаєте масив з одним елементом, тоді просто можна повертати і пустий масив, повертати null погана звичка, краще повертати один тип результату. Тоді в цій функції все зведеться до повернення результату фільтрації. Перевірку вище доведеться модифікувати. Можна навіть використати https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2022-10-22 17:52 UTC, Eastvarga commented on models/contacts.js
> +      data.splice(contactIdx, 1, newContact);
Це дуже важка логіка =)
є метод map котрий вирішує все при одному проходу по масиву
А у вас задіяно аж два проходи по массиву
const newData= data.map((elem)=>{ if(elem.id==contactId){return {body}} return elem})

2022-10-22 17:55 UTC, Eastvarga commented on routes/api/contacts.js
> +    res.status(200).json({ data, message: "Request processed successfully" });
message при статусі 200 не потрібен - якщо це не частина самої логіки - зайве, {data} достатньо

2022-10-22 17:55 UTC, Eastvarga commented on routes/api/contacts.js
> +  } catch (err) {
теж саме

2022-10-22 18:00 UTC, Eastvarga commented on validation.js
> +          "Phone number must be digits and can contain spaces, dashes, parentheses and can start with +",
Дуже поганий опис валідації =)
краще привести приклад +ХХХ-ХХХ бо не глянувши патерн не зрозумієш

2022-10-22 18:02 UTC, Eastvarga requested changes
Добра работа, але треба виправити деякі помилки

2022-10-30 17:20 UTC, DaryaGrygorova commented on models/contacts.js
> +    return JSON.parse(res);
Додано  функцію getContactsFromBD

2022-10-30 17:21 UTC, DaryaGrygorova commented on models/contacts.js
> +    const data = JSON.parse(res);
Додано  функцію getContactsFromBD

2022-10-30 17:29 UTC, DaryaGrygorova commented on models/contacts.js
> +    return contact;
Прибрала. Точніше, змінила метод визначення знаходження потрібного контакту в массиві з filter  на find.  Функція повертає результат роботи метода.  Відповідно, перевірка значення прописана у місці виклику функції

2022-10-30 17:34 UTC, DaryaGrygorova commented on models/contacts.js
> +      data.splice(contactIdx, 1, newContact);
Поправила. Зробила через .map

2022-10-30 17:37 UTC, DaryaGrygorova commented on routes/api/contacts.js
> +    res.status(200).json({ data, message: "Request processed successfully" });
Прибрала message для всіх "успішних" responses .

2022-10-30 17:37 UTC, DaryaGrygorova commented on routes/api/contacts.js
> +  } catch (err) {
Прибрала message для всіх "успішних" responses

2022-10-30 17:38 UTC, DaryaGrygorova commented on validation.js
> +          "Phone number must be digits and can contain spaces, dashes, parentheses and can start with +",
Додала до опису валідації приклади валідних форматів.

2022-10-30 17:42 UTC, DaryaGrygorova commented on .env_exemple
> +PORT=
Оригінальний файл .env прописаний у виключеннях .gitignore та не потропляє у репозіторій. Файл з розширенням  .env_exemple створено навмисно, для розуміння, які саме  змінні винесено у оточення (тільки перелік назв, без значень)

2022-10-30 18:05 UTC, Eastvarga commented on models/contacts.js
> +          return newContact;
Є трохи краще рішення для логіки апдейту, якщо айді співпадвє  повертаемо об''єкт з деструкцією попереднього елементу, та після цього деструкцію тіла з оновлюючими даними - але це діє коли імена полів елементу та тіла запиту співпадають. Але це Вам до уваги інформація

2022-10-30 18:07 UTC, Eastvarga commented on routes/api/contacts.js
> +    res.status(200).json({ data });
не треба в об'єкт вносити data:  ({data}) => (data)

2022-10-30 18:14 UTC, Eastvarga approved these changes
Добре попрацювали.
Робота прийнята, є зауваження, але вони не критичні

2022-10-30 18:14 UTC, merged