Hw05 avatars
DaryaGrygorova/goit-nodeJS-REST_API pull request #4
Opened 2022-11-20 17:47 UTC by DaryaGrygorova

2022-11-21 15:56 UTC, Eastvarga requested changes
Без теки public/avatars код не буде працювати для зображень. До того ж слеш напевно не в той бік дивиться

2022-11-22 09:43 UTC, DaryaGrygorova commented
> Без теки public/avatars code не будет працювати для изображения. До того ж слеш напевно не в той бік дивиться

Додала функцію що створює на сервері необхідні папки якщо вони не існують. Виконується перед стартом сервера. 
Слеш у відповіді користувачу поправила.

2022-11-22 14:10 UTC, Eastvarga commented on controllers/auth.controller.js
> +      { avatarURL: `avatars/${file.filename}` },
avatarURL: http://localhost:3000/avatars/my%20photo%20mini-noQwQk.jpg
Ось як повинен виглядати линк для зображення. (Використовуючи його у браузері Ви повинні отримати зображнення від сервера

2022-11-22 14:10 UTC, Eastvarga requested changes
Добре, але залишився маленький штрих

2022-11-22 15:25 UTC, DaryaGrygorova commented on controllers/auth.controller.js
> +      { avatarURL: `avatars/${file.filename}` },
Поправила

2022-11-22 16:20 UTC, Eastvarga approved these changes

2022-11-22 16:20 UTC, merged